# Building a Java project
language: java

# We can specify a list of JDKs to be used for testing
jdk:
 - openjdk11
after_success:
  - bash <(curl -s https://codecov.io/bash)
  deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file:
    default.travis.yml
  on:
    tags: true
    branch: knowingNothing
    repo: <FWLJCL>/<Travis_CI_Tutorial>
notifications:
 email:
   3106886964@qq.com(replace by your e-mail)


